//Created by dopieralad on 2018/04/26.

#ifndef GRAPHICS_OPENGL_PROJECT_ERRORS_H
#define GRAPHICS_OPENGL_PROJECT_ERRORS_H


class Errors {
public:
	/**
	 * Handles errors generated by OpenGL.
	 *
	 * @param exit_code OpenGL error code.
	 * @param details OpenGL error description.
	 */
	static void opengl_error_callback(int exit_code, const char* details);

	static void handle_fatal(int exit_code, const char* details);
	static void handle_fatal(const char* details);

private:
	Errors() = default; //Disallow instantiating this class as it should be a static class
};


#endif //GRAPHICS_OPENGL_PROJECT_ERRORS_H
